project_id = "fwwmdzxwxxwcmzhdvjfj"

[auth]
enabled = true

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.process-transcript]
verify_jwt = true

[functions.generate-summary]
verify_jwt = true

[functions.generate-email]
verify_jwt = true

[functions.extract-action-items]
verify_jwt = true

[functions.export-user-data]
verify_jwt = true

[functions.delete-user-data]
verify_jwt = true

[functions.health]
verify_jwt = false